/*// programm to find even or add of two no's.
#include<stdio.h>
#include<conio.h>
void main()
{
int a;
clrscr();
printf("Enter the value of a:");
scanf("%d",&a);
if(a%2==0)
printf(" %d is even",a);
if(a%2!=0)
printf(" %d is odd",a);
getch();
} */


// programm to find +ve and -ve.
#include<stdio.h>
#include<conio.h>
void main()
{
int a;
clrscr();
printf("Enter the value of a:");
scanf("%d",&a);
if(a>0)
printf(" %d is +ve",a);
else
printf(" %d is -ve",a);
getch();
}




