//program to print biodata.
#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
printf("      \n*****************************************");
printf("      \n                 RESUME");
printf("      \n    Name           :       ABC");
printf("      \n    Address	   :       XYZ");
printf("      \n    City           :       Hubli");
printf("      \n    DOB            :       01-01-0000");
printf("      \n                  END");
printf("      \n*****************************************");
getch();
}