/*   //program to find simple intrest,
 #include<stdio.h>
 #include<conio.h>
 void main()
{
int p,t;
float si,r;
clrscr();
printf("enter the value of p,t and r");
scanf("%d%d%f",&p,&t,&r);
si=(p*t*r)/100;
printf("\nsimple interest:=%f",si);
getch();
} */
/*  //program to find area and perimeter of square,
 #include<stdio.h>
 #include<conio.h>
 void main()
{
int a;
float area,peri;
clrscr();
printf("enter the value of a:");
scanf("%d",&a);
area=a*a;
peri=2*a;
printf("\n     area:=%f",area);
printf("\nperimeter:=%f",peri);
getch();
} */
/* //program to find area and perimeter of rectangle,
 #include<stdio.h>
 #include<conio.h>
 void main()
{
int l,b;
float area,peri;
clrscr();
printf("enter the value of  l and b:");
scanf("%d%d",&l,&b);
area=l*b;
peri=2*(l+b);
printf("\n     area:=%f",area);
printf("\nperimeter:=%f",peri);
getch();
}*/

 //program to find area and perimeter of circle,
 #include<stdio.h>
 #include<conio.h>
 void main()
{
int r;
float area,peri;
clrscr();
printf("enter the value of r:");
scanf("%d",&r);
area=r*r;
peri=3.142*r*r;
printf("\n     area:=%f",area);
printf("\nperimeter:=%f",peri);
getch();
}


