//cpp program to display employee information

#include<iostream.h>
#include<conio.h>

void main()
{
    clrscr();
    cout<<"\n****EMPLOYEE INFO***********\n";
    cout<<"\n emp name=xyz\n";
    cout<<"\n emp id=123\n";
    cout<<"\n emp_sal=10000\n";
    cout<<"\n emp_add=hubli";
//    cout<<"\n emplyee info\n name=xyz\n emp id=123\nempl_sal=10000\nemp_add=hubli\n";
    getch();
}

