#include<stdio.h>
#include<conio.h>
void main()
{
  clrscr();
  printf("\n int=%d",sizeof(int));
    printf("\n float=%d",sizeof(float));
      printf("\n charecter=%d",sizeof(char));
	printf("\n double=%d",sizeof(double));
	 printf("\n short=%d",sizeof(short));
	   printf("\n long=%d",sizeof(long));
	     printf("\n signed=%d",sizeof(signed));
	       printf("\n unsigned=%d",sizeof(unsigned));
	       getch();
	       }
