//program to print the message.
#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
printf("********************biodata**************************");
printf("\n      welcome to c program");
printf("\n      name      :   sangeeta");
printf("\n   address      :   barker");
printf("\n    d of b      :   31.7.1995");
printf("\n education      :   b,com");
printf("\n      place      :   at. chikknarthi tq.");
printf("\n                    kundgol ds.darawad");
printf("\n***********************END***************************");
getch();
}
