/*//wap to print simple program.
#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
printf("\n\n     welcome to c program");
getch();
} */

//wap to print BIODATA.
#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
printf("\n\n----------------------------------------");
printf("\n            RESUME");
printf("\n         Name  :  Keonics");
printf("\n      Address  :  IT Park");
printf("\n         CITY  :  Hubli");
printf("\n\n************END*************************");
getch();
}

